### ISSUE TITLE
FastAPI memory usage pile up and OOM error

### ISSUE THREAD

**Issue by dfhssilva** [NOVA-IMS-Innovation-and-Analytics-Lab/MapIntel#35]
It seems that after calling an endpoint (at least news-upload presents this behaviour), memory usage will not recover to the levels prior to calling. This eventually leads to OOM errors. Check the links below with relevant issue threads regarding this.
- [https://github.com/tiangolo/fastapi/issues/1624](https://github.com/tiangolo/fastapi/issues/1624)
- [https://github.com/tiangolo/fastapi/issues/596](https://github.com/tiangolo/fastapi/issues/596)
- [https://fastapi.tiangolo.com/async/](https://fastapi.tiangolo.com/async/)

**Comment by krstp** [comment]
FYI: Seems the issue still persists.
