### ISSUE TITLE
Deploy app

### ISSUE THREAD

**Issue by georgedouzas** [NOVA-IMS-Innovation-and-Analytics-Lab/MapIntel#80]
We should have a version deployed. I suggest the following steps:

1. Finish with issue #78.
2. Use Heroku or a similar cloud platform to deploy the app.

**Comment by stuartgo** [comment]
Currently the app relies on an elasticsearch database, and while testing it was only using a free trial. It should be enough for the demo as well I believe. Or should we set up our own database on the deployment?

**Comment by georgedouzas** [comment]
Let's try to do the minimum changes. I propose to use it as it is already set up.

**Comment by georgedouzas** [comment]
> We should have a version deployed. I suggest the following steps:
> 
> 1. Finish with issue [Rename tests #78](https://github.com/NOVA-IMS-Innovation-and-Analytics-Lab/MapIntel/issues/78).
> 2. Use Heroku or a similar cloud platform to deploy the app.

Let's check our options for cloud platforms.

**Comment by stuartgo** [comment]
Ok sure, Ill double check that everything runs also
